language: node_js
node_js:
  - 20 # 选择你需要的 Node.js 版本

services:
  - docker # 启用 Docker

before_install:
  # 打印 Docker 版本（可选）
  - docker --version

script:
  # 构建 Docker 镜像，使用 dockerfile.dev 作为构建文件
  - docker build -f dockerfile.dev -t nextjs-app .

  # 在 Docker 容器内运行 lint
  - docker run nextjs-app npm run lint

  # 在 Docker 容器内运行 build
  - docker run nextjs-app npm run build

  # 启动服务以便进行进一步测试（如果有需要）
  - docker run -d -p 3000:3000 nextjs-app
  - sleep 15 # 等待服务启动
  - curl -f http://localhost:3000 || travis_terminate 1 # 检查服务是否可访问

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "$name"
#   path: docker
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
