FROM node:alpine
ARG SETUP_ENVINROMENT=production
WORKDIR "/app"

COPY package.json .
RUN npm install
# Copy the .env{SETUP_ENVINROMENT} file to the container
# This will copy the .env.production.sample -> .env file if the SETUP_ENVINROMENT is production
COPY .env.$SETUP_ENVINROMENT.sample .env
COPY . .

 
CMD ["npm","run","dev"]
# 暴露端口  
EXPOSE 3000 