FROM node:alpine

ARG supabaseUrl
ARG supabaseKey

ENV SUPABASE_URL=$supabaseUrl  
ENV SUPABASE_KEY=$supabaseKey

WORKDIR "/app"

COPY package.json .
RUN npm install


COPY . .

 
CMD ["npm","run","dev"]
# 暴露端口  
EXPOSE 3000 