name: Build and Lint with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t nextjs-app:latest -f Dockerfile.dev .

      - name: Run lint inside Docker
        run: docker run --rm nextjs-app:latest npm run lint

      - name: Run build inside Docker
        run: docker run --rm -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} -e SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} nextjs-app:latest npm run build

      - name: Clean up Docker images
        run: docker rmi nextjs-app:latest

